import { useMemo } from 'react'
import { Users, UserCheck, Clock3, UserX, IndianRupee, AlertCircle } from 'lucide-react'
import StatsCard from '@/components/admin/StatsCard'
import { useTable } from '@/hooks/useGymData'
import { memberStatus, money, dateText, dueAmount } from '@/utils/format'
export default function AdminDashboard(){
 const {data:members,loading}=useTable('members','*,membership_plans(name,price)',{order:'created_at',ascending:false})
 const stats=useMemo(()=>{let active=0,exp=0,expired=0,paid=0,due=0,revenue=0;members.forEach(m=>{const s=memberStatus(m.expiry_date);if(s==='active')active++;else if(s==='expiring')exp++;else expired++;paid+=Number(m.amount_paid||0);revenue+=Number(m.amount_paid||0);due+=dueAmount(m.membership_plans?.price,m.amount_paid)});return{active,exp,expired,paid,due,revenue}},[members])
 return <div><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="eyebrow">Overview</div><h1 className="mt-2 font-display text-3xl font-bold">Dashboard</h1></div><div className="text-xs text-white/30">Live values from Supabase</div></div>
 <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[[Users,'Total Members',members.length],[UserCheck,'Active',stats.active],[Clock3,'Expiring ≤ 7d',stats.exp],[UserX,'Expired',stats.expired],[IndianRupee,'Collected',money(stats.revenue)],[AlertCircle,'Outstanding',money(stats.due)]].map(([I,t,v])=><StatsCard key={t} icon={I} title={t} value={v}/>)}</div>
 <div className="mt-8 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><div className="premium-card overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-semibold">Recent members</h2></div><div className="overflow-x-auto">{loading?<div className="p-8 text-white/35">Loading…</div>:members.slice(0,8).map(m=><div key={m.id} className="flex min-w-[520px] items-center justify-between border-b border-white/5 px-5 py-4 last:border-0"><div><div className="text-sm font-semibold">{m.full_name}</div><div className="mt-1 text-xs text-white/30">{m.membership_plans?.name||'No plan'} · expires {dateText(m.expiry_date)}</div></div><div className="text-right"><div className="text-sm font-semibold">{money(m.amount_paid)}</div><div className="text-[10px] uppercase tracking-[.12em] text-white/30">{memberStatus(m.expiry_date)}</div></div></div>)}</div></div>
 <div className="premium-card p-6"><div className="eyebrow">Status mix</div><div className="mt-7 space-y-5">{[['Active',stats.active],['Expiring soon',stats.exp],['Expired',stats.expired]].map(([x,n])=><div key={x}><div className="flex justify-between text-xs"><span className="text-white/50">{x}</span><span>{n}</span></div><div className="mt-2 h-1.5 bg-white/10"><div className="h-full bg-power-400" style={{width:`${members.length?Math.max(4,n/members.length*100):0}%`}}/></div></div>)}</div></div></div></div>
}