import { useEffect, useState } from 'react'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { requireSupabase } from '@/lib/supabase'
import { useSupabaseUpload } from '@/hooks/useSupabaseUpload'
const blank={name:'',description:'',image_url:'',icon:''}
export default function Facilities(){
 const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[edit,setEdit]=useState(null);const {uploadFile,isUploading}=useSupabaseUpload('facilities')
 const load=async()=>{const {data}=await requireSupabase().from('facilities').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();try{const q=edit?requireSupabase().from('facilities').update(form).eq('id',edit):requireSupabase().from('facilities').insert(form);const {error}=await q;if(error)throw error;setForm(blank);setEdit(null);load()}catch(e){alert(e.message)}}
 const photo=async e=>{const f=e.target.files?.[0];if(!f)return;const r=await uploadFile(f,'facilities');setForm(x=>({...x,image_url:r.publicUrl}))}
 const del=async id=>{if(!confirm('Delete this facility?'))return;const {error}=await requireSupabase().from('facilities').delete().eq('id',id);if(error)alert(error.message);else load()}
 return <div><div className="eyebrow">CMS</div><h1 className="mt-2 font-display text-3xl font-bold">Facilities</h1><div className="mt-8 grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={save} className="premium-card p-6 space-y-4"><label><span className="label">Name *</span><input required className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span className="label">Description</span><textarea className="field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label><span className="label">Image</span><input type="file" accept="image/*" onChange={photo} className="field file:mr-3 file:border-0 file:bg-white/10 file:px-3 file:py-2"/>{form.image_url&&<img src={form.image_url} alt="" className="mt-3 h-24 w-full object-cover border border-white/10"/>}</label><button className="btn-primary w-full">{isUploading?'Uploading…':edit?'Update facility':'Add facility'}</button>{edit&&<button type="button" className="btn-secondary w-full" onClick={()=>{setEdit(null);setForm(blank)}}>Cancel</button>}</form><div className="grid gap-3 sm:grid-cols-2">{rows.map(r=><div key={r.id} className="premium-card overflow-hidden"><div className="aspect-[4/2] bg-white/[.03]">{r.image_url&&<img src={r.image_url} alt={r.name} className="h-full w-full object-cover"/>}</div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{r.name}</h3><p className="mt-1 text-xs leading-5 text-white/35">{r.description}</p></div><div className="flex gap-1"><button onClick={()=>{setEdit(r.id);setForm(r)}} className="h-fit border border-white/10 p-2"><Pencil size={14}/></button><button onClick={()=>del(r.id)} className="h-fit border border-white/10 p-2 text-red-300"><Trash2 size={14}/></button></div></div></div></div>)}{!rows.length&&<div className="border border-dashed border-white/15 p-10 text-center text-white/35 sm:col-span-2">No facilities yet.</div>}</div></div></div>
}