import { useEffect, useState } from 'react'
import { Trash2, Upload } from 'lucide-react'
import { requireSupabase } from '@/lib/supabase'
import { useSupabaseUpload } from '@/hooks/useSupabaseUpload'
export default function GalleryAdmin(){
 const [rows,setRows]=useState([]),[caption,setCaption]=useState(''),[type,setType]=useState('image');const {uploadFile,isUploading}=useSupabaseUpload('gallery')
 const load=async()=>{const {data}=await requireSupabase().from('gallery_items').select('*').order('created_at',{ascending:false});setRows(data||[])};useEffect(()=>{load()},[])
 const upload=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await uploadFile(f,'gallery');const {error}=await requireSupabase().from('gallery_items').insert({type,url:r.publicUrl,caption:caption||null});if(error)throw error;setCaption('');load()}catch(err){alert(err.message)}e.target.value=''}
 const del=async row=>{if(!confirm('Delete this gallery item?'))return;const {error}=await requireSupabase().from('gallery_items').delete().eq('id',row.id);if(error)alert(error.message);else load()}
 return <div><div className="eyebrow">CMS</div><h1 className="mt-2 font-display text-3xl font-bold">Gallery</h1><div className="premium-card mt-8 p-6"><div className="grid gap-4 sm:grid-cols-[180px_1fr_auto]"><select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="image">Image</option><option value="video">Video</option></select><input className="field" placeholder="Caption (optional)" value={caption} onChange={e=>setCaption(e.target.value)}/><label className="btn-primary cursor-pointer"><Upload size={16}/>{isUploading?'Uploading…':'Upload'}<input type="file" accept={type==='image'?'image/*':'video/*'} onChange={upload} className="hidden"/></label></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><div key={r.id} className="premium-card overflow-hidden"><div className="aspect-video bg-white/[.03]">{r.type==='video'?<video src={r.url} controls className="h-full w-full object-cover"/>:<img src={r.url} alt={r.caption||''} className="h-full w-full object-cover"/>}</div><div className="flex items-center justify-between p-4"><span className="text-xs text-white/40">{r.caption||'No caption'}</span><button onClick={()=>del(r)} className="border border-white/10 p-2 text-red-300"><Trash2 size={14}/></button></div></div>)}</div></div>
}