import { Link } from 'react-router-dom'
import { useMemo, useState } from 'react'
import { Plus, Search, Pencil, Trash2 } from 'lucide-react'
import { requireSupabase } from '@/lib/supabase'
import { useTable } from '@/hooks/useGymData'
import { dateText, memberStatus, waLink, money, paymentStatus, dueAmount } from '@/utils/format'
import WhatsAppIcon from '@/components/WhatsAppIcon'

export default function Members(){
 const {data,reload,loading}=useTable('members','*,membership_plans(name,price)',{order:'created_at',ascending:false});const [q,setQ]=useState('');const [filter,setFilter]=useState('all')
 const rows=useMemo(()=>data.filter(m=>(m.full_name.toLowerCase().includes(q.toLowerCase())||m.phone.includes(q))).filter(m=>{const ps=paymentStatus(m.membership_plans?.price,m.amount_paid); return filter==='all'||(filter==='paid'?ps==='paid':filter==='due'?ps!=='paid':memberStatus(m.expiry_date)===filter)}),[data,q,filter])
 const del=async id=>{if(!confirm('Delete this member? This cannot be undone.'))return;const {error}=await requireSupabase().from('members').delete().eq('id',id);if(error)alert(error.message);else reload()}
 return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="eyebrow">Member management</div><h1 className="mt-2 font-display text-3xl font-bold">Members</h1></div><Link to="/admin/members/new" className="btn-primary"><Plus size={17}/> Add member</Link></div>
 <div className="mt-7 flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 text-white/25" size={17}/><input className="field pl-10" placeholder="Search name or phone…" value={q} onChange={e=>setQ(e.target.value)}/></div><select className="field md:w-48" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="expiring">Expiring soon</option><option value="expired">Expired</option><option value="paid">Paid</option><option value="due">Due</option></select></div>
 <div className="premium-card mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[980px] w-full text-left"><thead className="bg-white/[.025] text-[10px] uppercase tracking-[.15em] text-white/30"><tr>{['Member','Plan','Expiry','Paid','Due','Payment','Status','Actions'].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="8" className="p-10 text-center text-white/35">Loading members…</td></tr>:rows.length?rows.map(m=>{const s=memberStatus(m.expiry_date);const ps=paymentStatus(m.membership_plans?.price,m.amount_paid);const due=dueAmount(m.membership_plans?.price,m.amount_paid);const msg=`Hi ${m.full_name}, your Power Fitness membership is ${s==='expired'?'expired':'expiring'} on ${dateText(m.expiry_date)}. Please contact us for renewal.`;return <tr key={m.id} className="border-t border-white/5"><td className="px-5 py-4"><Link to={`/admin/members/${m.id}`} className="font-semibold text-white transition hover:text-power-300 hover:underline underline-offset-4">{m.full_name}</Link><div className="mt-1 text-xs text-white/30">{m.phone}</div></td><td className="px-5 py-4 text-sm text-white/60">{m.membership_plans?.name||'—'}</td><td className="px-5 py-4 text-sm text-white/60">{dateText(m.expiry_date)}</td><td className="px-5 py-4 text-sm">{money(m.amount_paid)}</td><td className="px-5 py-4 text-sm font-semibold">{money(due)}</td><td className="px-5 py-4"><span className={`inline-flex border px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.12em] ${ps==='paid'?'border-emerald-400/20 bg-emerald-400/10 text-emerald-300':ps==='partial'?'border-amber-400/20 bg-amber-400/10 text-amber-300':'border-red-400/20 bg-red-400/10 text-red-300'}`}>{ps}</span></td><td className="px-5 py-4"><span className={`text-[10px] font-bold uppercase tracking-[.12em] ${s==='active'?'text-emerald-300':s==='expiring'?'text-amber-300':'text-red-300'}`}>{s}</span></td><td className="px-5 py-4"><div className="flex items-center gap-2"><a title="WhatsApp" aria-label={`WhatsApp ${m.full_name}`} href={waLink(m.phone,msg)} target="_blank" rel="noreferrer" className="inline-flex h-9 w-9 items-center justify-center border border-emerald-400/20 bg-emerald-400/10 text-emerald-300 transition hover:border-emerald-300/40 hover:bg-emerald-400/20"><WhatsAppIcon size={18}/></a><Link title="Edit" to={`/admin/members/${m.id}/edit`} className="inline-flex h-9 w-9 items-center justify-center border border-white/10 hover:bg-white/5"><Pencil size={15}/></Link><button title="Delete" onClick={()=>del(m.id)} className="inline-flex h-9 w-9 items-center justify-center border border-white/10 text-red-300 hover:bg-red-400/10"><Trash2 size={15}/></button></div></td></tr>}) : <tr><td colSpan="8" className="p-12 text-center text-white/35">No members found.</td></tr>}</tbody></table></div></div>
 </div>
}
