import { useEffect, useState } from 'react'
import { Pencil, Plus, Trash2 } from 'lucide-react'
import { requireSupabase } from '@/lib/supabase'
import { money } from '@/utils/format'
const blank={name:'',duration_months:12,price:'',description:'',is_featured:false}
export default function Plans(){
 const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[edit,setEdit]=useState(null),[busy,setBusy]=useState(false)
 const load=async()=>{const {data}=await requireSupabase().from('membership_plans').select('*').order('price',{ascending:true});setRows(data||[])};useEffect(()=>{load()},[])
 const save=async e=>{e.preventDefault();setBusy(true);try{const payload={...form,duration_months:Number(form.duration_months),price:Number(form.price)};const q=edit?requireSupabase().from('membership_plans').update(payload).eq('id',edit):requireSupabase().from('membership_plans').insert(payload);const {error}=await q;if(error)throw error;setForm(blank);setEdit(null);await load()}catch(e){alert(e.message)}finally{setBusy(false)}}
 const del=async id=>{if(!confirm('Delete this plan? Existing members keep their membership record, but the plan may no longer be selectable.'))return;const {error}=await requireSupabase().from('membership_plans').delete().eq('id',id);if(error)alert(error.message);else load()}
 return <div><div className="flex justify-between items-end"><div><div className="eyebrow">CMS</div><h1 className="mt-2 font-display text-3xl font-bold">Membership plans</h1></div></div>
 <div className="mt-8 grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={save} className="premium-card p-6"><div className="grid gap-4">{[['name','Plan name','text'],['duration_months','Duration (months)','number'],['price','Price (₹)','number']].map(([k,l,t])=><label key={k}><span className="label">{l}</span><input className="field" required value={form[k]} type={t} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label><span className="label">Description</span><textarea className="field min-h-24" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="flex gap-3 text-sm text-white/60"><input type="checkbox" checked={form.is_featured} onChange={e=>setForm({...form,is_featured:e.target.checked})}/> Featured plan</label><button className="btn-primary w-full" disabled={busy}>{edit?'Update plan':'Add plan'}</button>{edit&&<button type="button" className="btn-secondary w-full" onClick={()=>{setEdit(null);setForm(blank)}}>Cancel edit</button>}</div></form>
 <div className="space-y-3">{rows.map(p=><div key={p.id} className="premium-card flex items-center justify-between gap-4 p-5"><div><div className="text-xs text-power-300">{p.duration_months} months</div><h3 className="mt-1 font-display text-xl font-semibold">{p.name}</h3><div className="mt-1 text-sm text-white/40">{money(p.price)}</div></div><div className="flex gap-2"><button onClick={()=>{setEdit(p.id);setForm(p)}} className="border border-white/10 p-2"><Pencil size={15}/></button><button onClick={()=>del(p.id)} className="border border-white/10 p-2 text-red-300"><Trash2 size={15}/></button></div></div>)}{!rows.length&&<div className="border border-dashed border-white/15 p-10 text-center text-white/35">No plans yet. Add the first one.</div>}</div></div></div>
}