import { useEffect, useState } from 'react'
import { requireSupabase } from '@/lib/supabase'
import { useAuth } from '@/hooks/useAuth'
const blank={name:'POWER FITNESS HEALTH CLUB GYM',owner_name:'Mukesh Kumar Jagrat',whatsapp:'+91 99296 56539',instagram:'@power_fitness_healthclub_gym',address:'Plot No. 67, Mukund Vihar Colony, Near Study Base Library, Adarsh Nagar, Ajmer, Rajasthan - 305003',google_maps_url:'https://maps.app.goo.gl/vjHAwZynNLBQK3TRA?g_st=ac',about_content:'',hero_headline:'',hero_subtext:'',opening_hours:{}}
export default function Settings(){
 const [form,setForm]=useState(blank),[id,setId]=useState(null),[busy,setBusy]=useState(false),[pw,setPw]=useState('');const {changePassword}=useAuth()
 useEffect(()=>{requireSupabase().from('gym_settings').select('*').limit(1).maybeSingle().then(({data})=>{if(data){setForm({...blank,...data});setId(data.id)}})},[])
 const save=async e=>{e.preventDefault();setBusy(true);try{const q=id?requireSupabase().from('gym_settings').update({...form,updated_at:new Date().toISOString()}).eq('id',id):requireSupabase().from('gym_settings').insert(form);const {error}=await q;if(error)throw error;alert('Settings saved.')}catch(e){alert(e.message)}finally{setBusy(false)}}
 const password=async e=>{e.preventDefault();if(pw.length<8)return alert('Use at least 8 characters.');try{await changePassword(pw);setPw('');alert('Password changed.')}catch(e){alert(e.message)}}
 const set=(k,v)=>setForm(x=>({...x,[k]:v}))
 return <div className="max-w-5xl"><div className="eyebrow">CMS + account</div><h1 className="mt-2 font-display text-3xl font-bold">Settings</h1><form onSubmit={save} className="premium-card mt-8 p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{[['name','Gym name'],['owner_name','Owner name'],['whatsapp','WhatsApp / phone'],['instagram','Instagram handle'],['address','Address'],['google_maps_url','Google Maps URL']].map(([k,l])=><label key={k} className={k==='address'?'sm:col-span-2':''}><span className="label">{l}</span><input className="field" value={form[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}<label className="sm:col-span-2"><span className="label">About content</span><textarea className="field min-h-32" value={form.about_content||''} onChange={e=>set('about_content',e.target.value)}/></label><label className="sm:col-span-2"><span className="label">Hero headline</span><input className="field" value={form.hero_headline||''} onChange={e=>set('hero_headline',e.target.value)}/></label><label className="sm:col-span-2"><span className="label">Hero subtext</span><textarea className="field min-h-24" value={form.hero_subtext||''} onChange={e=>set('hero_subtext',e.target.value)}/></label></div><button className="btn-primary mt-6" disabled={busy}>{busy?'Saving…':'Save website settings'}</button></form>
 <form onSubmit={password} className="premium-card mt-5 p-6 sm:p-8"><div className="eyebrow">Security</div><h2 className="mt-2 font-display text-2xl font-semibold">Change admin password</h2><div className="mt-5 flex flex-col gap-3 sm:flex-row"><input className="field" type="password" minLength="8" placeholder="New password (8+ characters)" value={pw} onChange={e=>setPw(e.target.value)} required/><button className="btn-secondary">Change password</button></div></form>
 </div>
}